######################################################################
##
## Filename: sbox_vtb.udo
## Created on: Fri Feb 21 15:02:19 GMT 标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
