######################################################################
##
## Filename: Sbox_tb.udo
## Created on: Tue Feb 18 15:16:34 GMT 标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
