######################################################################
##
## Filename: TOP_tb.udo
## Created on: Sat Mar 21 12:50:33 GMT 标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
